### ISSUE TITLE
Travis build uses after_success to deploy, which gives a false success

### ISSUE THREAD

**Issue by humblelistener** [PageUpPeopleOrg/microservice-bootstrap#1]
In the commit 258f13f212f737abccf91a79db1fce6b4041fce0 , I had to change from deploy to after_success before deploy did not support an array.

This is reported as a bug in travis ci travis-ci/travis-ci/issues/4673

Need to fix this back to deploy step or any step between script and completion without compromising on the output.

**Comment by humblelistener** [comment]
not relevant any more

**Comment by jimmyp** [comment]
@humblelistener if deploy fails will the build fail?

**Comment by humblelistener** [comment]
Are you asking about `after_sucess` in travis? 
It does not fail the build if the deploy fails if deployment is in after success section.

https://docs.travis-ci.com/user/customizing-the-build/

should micro service bootstrap have the deployment in the `after_success` section? NO

But given Travis file does not have this section at the moment, this is not relevant a.t.m.

**Comment by jimmyp** [comment]
I was asking in its current form would a failed deploy fail the build.
Sounds like the answer is yes?
