### ISSUE TITLE
Is dockercompose port mapping needed?

### ISSUE THREAD

**Issue by antonfelich** [PageUpPeopleOrg/microservice-bootstrap#44]
Dockercompose was mapping port 4000 -> 4001 and baking that into the docker image, we have to make it 4000->4000 to get it to work. Notes around why this port mapping exists and how it works (maybe a container/stack diagram of ports)

**Comment by jimmyp** [comment]
The port mapping of the container should be dynamic and registering that dynamic port with the ALB. Otherwise you will get port collisions when 2 web tasks try to start on the same box

**Comment by humblelistener** [comment]
Yes, @jimmyp is correct.

In our context, docker compose is only used in the developer environment and should not affect how AWS ECS works. 

If the port mapping in docker compose file is confusing, we should just make it simple.

I will take a look
