### ISSUE TITLE
Use multi stage docker build

### ISSUE THREAD

**Issue by humblelistener** [PageUpPeopleOrg/microservice-bootstrap#51]
https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds

**Comment by mattbirman** [comment]
FYI we got this working in Wahoo. One caveat, it was tricky to get going with Travis. The version of Docker installed by default on Travis does not support multi-stage builds. So `docker-ce` needs to be installed. If then pushing the images to ECR, it needs to be uninstalled and default `docker` re-installed before pushing, as `docker-ce` does not push to ECR.
https://github.com/PageUpPeopleOrg/microservice-bootstrap/pull/50

**Comment by humblelistener** [comment]
I am seeing this being done by @antonfelich as well.oh.. I also see another such done by @antonfelich. Eventually, the changes should go into both API bootstrap and this repo eventually.

**Comment by humblelistener** [comment]
Thanks @mattbirman
